import os
from logging.config import fileConfig

from alembic import context
from mrr.persistence.tables import metadata as target_metadata
from sqlalchemy import create_engine, pool

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Autogenerate support against mrr.persistence.tables.metadata. The initial
# migration in versions/ is hand-written, not autogenerated, but future
# schema changes may use `alembic revision --autogenerate` against this
# metadata and then be reviewed before merge.

#: Environment variable read for real deployments (task-packets/E1-T05.yaml:
#: "Database URL comes from MRR_DATABASE_URL env"; "no credentials committed
#: anywhere"). alembic.ini deliberately leaves sqlalchemy.url unset.
_DATABASE_URL_ENV_VAR = "MRR_DATABASE_URL"

#: Key under `Config.attributes` (a plain Python dict on the Config object,
#: never parsed by configparser) that programmatic callers - e.g.
#: tests/integration/conftest.py - use to inject a URL directly.
_ATTRIBUTES_URL_KEY = "sqlalchemy_url"


def _resolve_database_url() -> str:
    """Resolve the database URL without ever routing it through
    configparser (i.e. never via `Config.set_main_option`/`get_main_option`/
    `get_section`, and never written into alembic.ini).

    configparser's default interpolation treats a bare ``%`` in a stored
    value as the start of an interpolation sequence
    (``configparser.InterpolationSyntaxError: invalid interpolation
    syntax``). The schema-scoped URLs tests/integration/conftest.py builds
    contain a percent-encoded query parameter
    (``options=-c%20search_path%3D<schema>``), so round-tripping them
    through ``set_main_option``/``get_section`` breaks. Two sources, checked
    in order, both of which bypass configparser entirely:

    1. ``config.attributes["sqlalchemy_url"]`` - Alembic's documented
       mechanism for injecting arbitrary Python objects into env.py,
       used by tests/integration/conftest.py.
    2. the ``MRR_DATABASE_URL`` environment variable - the path for real
       deployments and manual ``alembic upgrade``/``downgrade`` invocations.
    """
    attributes_url = config.attributes.get(_ATTRIBUTES_URL_KEY)
    if attributes_url:
        return str(attributes_url)

    env_url = os.environ.get(_DATABASE_URL_ENV_VAR)
    if env_url:
        return env_url

    raise RuntimeError(
        f"No database URL available: set config.attributes[{_ATTRIBUTES_URL_KEY!r}] "
        f"(programmatic callers) or the {_DATABASE_URL_ENV_VAR} environment variable "
        "(command-line usage). alembic.ini intentionally never carries one - no "
        "credentials are committed anywhere."
    )


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    context.configure(
        url=_resolve_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    Unlike the generic Alembic template, the engine is built directly from
    the resolved URL string (``create_engine``) rather than via
    ``engine_from_config(config.get_section(...))`` - the latter reads the
    URL back out of the configparser-backed option store, which is exactly
    the round-trip ``_resolve_database_url`` avoids.
    """
    connectable = create_engine(_resolve_database_url(), poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
