import os
from logging.config import fileConfig

from alembic import context
from mrr.persistence.tables import metadata as target_metadata
from sqlalchemy import engine_from_config, pool

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Autogenerate support against mrr.persistence.tables.metadata. The initial
# migration in versions/ is hand-written, not autogenerated, but future
# schema changes may use `alembic revision --autogenerate` against this
# metadata and then be reviewed before merge.

# The connection URL comes exclusively from the MRR_DATABASE_URL environment
# variable (task-packets/E1-T05.yaml: "no credentials committed anywhere").
# alembic.ini deliberately leaves sqlalchemy.url unset.
_DATABASE_URL_ENV_VAR = "MRR_DATABASE_URL"


def _require_database_url() -> str:
    url = os.environ.get(_DATABASE_URL_ENV_VAR)
    if not url:
        raise RuntimeError(
            f"{_DATABASE_URL_ENV_VAR} is not set. Alembic requires a database URL and does "
            "not read one from alembic.ini or any other committed file."
        )
    return url


config.set_main_option("sqlalchemy.url", _require_database_url())


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
