"""SQLAlchemy Core table definitions for the ``objects``/``edges`` tables
(task-packets/E1-T05.yaml derived_decisions: "one generic revisioned objects
table plus one typed edges table, not per-entity tables") and the
``domain_events``/``outbox`` tables (task-packets/E1-T06.yaml).

Core ``Table`` objects are used deliberately instead of the ORM's declarative
classes — less magic under mypy strict, and these tables are accessed only
through the repository implementations in
``mrr.persistence.repositories``, never mapped onto domain objects directly.

The schema created here MUST match ``migrations/versions/`` exactly; each
Alembic migration is hand-written (not autogenerated) but mirrors the
corresponding table column-for-column. If the two ever drift, integration
tests comparing live database structure against this metadata will surface
it.
"""

from __future__ import annotations

import sqlalchemy as sa
from mrr.domain.repositories import EDGE_VOCABULARY
from mrr.provenance.log import OUTBOX_STATUSES
from sqlalchemy.dialects import postgresql

metadata = sa.MetaData()

#: The IN-list clause for the ``edges.edge_type`` CHECK constraint, built
#: from the single source of truth for the vocabulary
#: (``mrr.domain.repositories.EDGE_VOCABULARY``) so this table definition can
#: never silently drift from the domain-layer fail-closed check in
#: ``mrr.persistence.repositories.PostgresEdgeRepository.add_edge``. The
#: initial migration hard-codes the equivalent literal list (migrations must
#: be self-contained, reviewable snapshots that don't import application
#: code) — see the module docstring above for the drift-detection story.
_EDGE_TYPE_LIST = ", ".join(f"'{t}'" for t in sorted(EDGE_VOCABULARY))
_EDGE_TYPE_CHECK_CLAUSE = f"edge_type IN ({_EDGE_TYPE_LIST})"

#: One generic, revisioned object-store table. Every first-class MRR object
#: (docs/spec/02_DOMAIN_MODEL.md section 1) is a row here; ``(id, revision)``
#: is the primary key, so a revision is always a new row — there is no
#: UPDATE or DELETE path anywhere in ``mrr.persistence.repositories``.
objects_table = sa.Table(
    "objects",
    metadata,
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("revision", sa.Integer(), nullable=False),
    sa.Column("api_version", sa.Text(), nullable=False),
    sa.Column("kind", sa.Text(), nullable=False),
    sa.Column("practice_id", sa.Text(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("created_by", sa.Text(), nullable=False),
    sa.Column("content_hash", sa.Text(), nullable=False),
    sa.Column("supersedes", sa.Text(), nullable=True),
    sa.Column("labels", postgresql.JSONB(), nullable=True),
    sa.Column("body", postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint("id", "revision", name="pk_objects"),
    sa.Index("ix_objects_kind", "kind"),
)

#: One generic typed-edge table for the claim/evidence graph
#: (docs/spec/02_DOMAIN_MODEL.md section 3). Edges are not revisioned — each
#: row is independent and append-only, identified by its own urn.
edges_table = sa.Table(
    "edges",
    metadata,
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("source_id", sa.Text(), nullable=False),
    sa.Column("target_id", sa.Text(), nullable=False),
    sa.Column("edge_type", sa.Text(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("created_by", sa.Text(), nullable=False),
    sa.Column("practice_id", sa.Text(), nullable=True),
    sa.Column("scope", postgresql.JSONB(), nullable=True),
    sa.Column("status", sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint("id", name="pk_edges"),
    sa.CheckConstraint(_EDGE_TYPE_CHECK_CLAUSE, name="ck_edges_edge_type_vocabulary"),
    sa.Index("ix_edges_source_id", "source_id"),
    sa.Index("ix_edges_target_id", "target_id"),
    sa.Index("ix_edges_edge_type", "edge_type"),
)

#: The IN-list clause for the ``outbox.status`` CHECK constraint, built from
#: the single source of truth for the vocabulary
#: (``mrr.provenance.log.OUTBOX_STATUSES``) — mirrors the
#: ``_EDGE_TYPE_CHECK_CLAUSE`` pattern above.
_OUTBOX_STATUS_LIST = ", ".join(f"'{s}'" for s in sorted(OUTBOX_STATUSES))
_OUTBOX_STATUS_CHECK_CLAUSE = f"status IN ({_OUTBOX_STATUS_LIST})"

#: The append-only domain event log (task-packets/E1-T06.yaml, MRR-NFR-002).
#: ``sequence`` is a database-generated identity so append order is decided
#: by the database itself, never by application code — there is no UPDATE or
#: DELETE path anywhere in ``mrr.persistence.repositories.PostgresEventLog``.
#: ``prev_hash`` is NULL only for the very first physical row ever inserted;
#: every later row's ``prev_hash`` is the previous row's ``content_hash``
#: (task-packets/E1-T06.yaml derived_decisions: "tamper evidence is a hash
#: chain").
domain_events_table = sa.Table(
    "domain_events",
    metadata,
    sa.Column("sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("event_type", sa.Text(), nullable=False),
    sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("actor", sa.Text(), nullable=False),
    sa.Column("policy_version", sa.Text(), nullable=False),
    sa.Column("causation_id", sa.Text(), nullable=True),
    sa.Column("correlation_id", sa.Text(), nullable=False),
    sa.Column("object_id", sa.Text(), nullable=False),
    sa.Column("object_revision", sa.Integer(), nullable=False),
    sa.Column("payload", postgresql.JSONB(), nullable=False),
    sa.Column("content_hash", sa.Text(), nullable=False),
    sa.Column("prev_hash", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("sequence", name="pk_domain_events"),
    sa.UniqueConstraint("id", name="uq_domain_events_id"),
    sa.Index("ix_domain_events_object_id", "object_id"),
    sa.Index("ix_domain_events_correlation_id", "correlation_id"),
)

#: The transactional outbox (task-packets/E1-T06.yaml, docs/spec/03_API_AND_
#: EVENTS.md section 5.3: "State changes and event publication MUST use a
#: transactional outbox so that committed domain changes cannot silently
#: lose their corresponding event"). One row per appended event, inserted in
#: the SAME transaction as its ``domain_events`` row
#: (``mrr.persistence.unit_of_work.record_object_revision_with_event``).
#: There is no UPDATE path that changes ``event_id`` or re-creates a
#: dispatched row — ``mrr.persistence.repositories.InProcessOutboxDispatcher``
#: only ever transitions a row's ``status``/``dispatched_at``/``attempts``.
outbox_table = sa.Table(
    "outbox",
    metadata,
    sa.Column("event_id", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("dispatched_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.PrimaryKeyConstraint("event_id", name="pk_outbox"),
    sa.ForeignKeyConstraint(["event_id"], ["domain_events.id"], name="fk_outbox_event_id"),
    sa.CheckConstraint(_OUTBOX_STATUS_CHECK_CLAUSE, name="ck_outbox_status_vocabulary"),
)
