"""SQLAlchemy Core table definitions for the ``objects`` and ``edges``
tables (task-packets/E1-T05.yaml derived_decisions: "one generic revisioned
objects table plus one typed edges table, not per-entity tables").

Core ``Table`` objects are used deliberately instead of the ORM's declarative
classes — less magic under mypy strict, and these tables are accessed only
through the repository implementations in
``mrr.persistence.repositories``, never mapped onto domain objects directly.

The schema created here MUST match ``migrations/versions/`` exactly; the
initial Alembic migration is hand-written (not autogenerated) but mirrors
this module column-for-column. If the two ever drift, integration tests
comparing live database structure against this metadata will surface it.
"""

from __future__ import annotations

import sqlalchemy as sa
from mrr.domain.repositories import EDGE_VOCABULARY
from sqlalchemy.dialects import postgresql

metadata = sa.MetaData()

#: The IN-list clause for the ``edges.edge_type`` CHECK constraint, built
#: from the single source of truth for the vocabulary
#: (``mrr.domain.repositories.EDGE_VOCABULARY``) so this table definition can
#: never silently drift from the domain-layer fail-closed check in
#: ``mrr.persistence.repositories.PostgresEdgeRepository.add_edge``. The
#: initial migration hard-codes the equivalent literal list (migrations must
#: be self-contained, reviewable snapshots that don't import application
#: code) — see the module docstring above for the drift-detection story.
_EDGE_TYPE_LIST = ", ".join(f"'{t}'" for t in sorted(EDGE_VOCABULARY))
_EDGE_TYPE_CHECK_CLAUSE = f"edge_type IN ({_EDGE_TYPE_LIST})"

#: One generic, revisioned object-store table. Every first-class MRR object
#: (docs/spec/02_DOMAIN_MODEL.md section 1) is a row here; ``(id, revision)``
#: is the primary key, so a revision is always a new row — there is no
#: UPDATE or DELETE path anywhere in ``mrr.persistence.repositories``.
objects_table = sa.Table(
    "objects",
    metadata,
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("revision", sa.Integer(), nullable=False),
    sa.Column("api_version", sa.Text(), nullable=False),
    sa.Column("kind", sa.Text(), nullable=False),
    sa.Column("practice_id", sa.Text(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("created_by", sa.Text(), nullable=False),
    sa.Column("content_hash", sa.Text(), nullable=False),
    sa.Column("supersedes", sa.Text(), nullable=True),
    sa.Column("labels", postgresql.JSONB(), nullable=True),
    sa.Column("body", postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint("id", "revision", name="pk_objects"),
    sa.Index("ix_objects_kind", "kind"),
)

#: One generic typed-edge table for the claim/evidence graph
#: (docs/spec/02_DOMAIN_MODEL.md section 3). Edges are not revisioned — each
#: row is independent and append-only, identified by its own urn.
edges_table = sa.Table(
    "edges",
    metadata,
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("source_id", sa.Text(), nullable=False),
    sa.Column("target_id", sa.Text(), nullable=False),
    sa.Column("edge_type", sa.Text(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("created_by", sa.Text(), nullable=False),
    sa.Column("practice_id", sa.Text(), nullable=True),
    sa.Column("scope", postgresql.JSONB(), nullable=True),
    sa.Column("status", sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint("id", name="pk_edges"),
    sa.CheckConstraint(_EDGE_TYPE_CHECK_CLAUSE, name="ck_edges_edge_type_vocabulary"),
    sa.Index("ix_edges_source_id", "source_id"),
    sa.Index("ix_edges_target_id", "target_id"),
    sa.Index("ix_edges_edge_type", "edge_type"),
)
