"""processed_ids table

Revision ID: 983751ff8bb6
Revises: b438bc0f8c0c
Create Date: 2026-07-20 00:00:00.000000

Hand-written, not autogenerated (same discipline as b9e7d0e3aff6 and
b438bc0f8c0c). Mirrors packages/persistence/mrr/persistence/tables.py
column-for-column:

- ``processed_ids``: the durable replay/idempotency store
  (task-packets/E5-T07.yaml) backing ``mrr.domain.envelope_validation.
  AlreadyProcessed`` (over ``message_id``) and ``mrr.domain.offline_bundle.
  BundleAlreadyProcessed`` (over ``bundle_id``). Primary key
  ``(recipient_node_id, id)`` is also this table's UNIQUE constraint and the
  sole idempotency anchor ``mrr.persistence.repositories.
  PostgresProcessedIdStore.record_processed`` targets with
  ``INSERT ... ON CONFLICT DO NOTHING``. ``id_kind`` is constrained by a
  CHECK against the exact two-value vocabulary, deliberately hard-coded as a
  literal list rather than imported from mrr.domain — migrations are
  self-contained, reviewable snapshots that must not depend on application
  code that could change after this migration is committed. The literal
  list below MUST match mrr.domain.replay_retention.PROCESSED_ID_KINDS as it
  stood when this migration was authored; a future vocabulary change
  requires its own migration, not an edit to this file. ``expires_at`` is
  indexed to support ``prune_expired``'s candidate prefilter
  (``expires_at <= now``). There is no UPDATE path for this table anywhere
  in ``PostgresProcessedIdStore`` — a row is appended once by
  ``record_processed`` and later removed only by ``prune_expired``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "983751ff8bb6"
down_revision: str | Sequence[str] | None = "b438bc0f8c0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Verbatim snapshot of mrr.domain.replay_retention.PROCESSED_ID_KINDS at
#: authoring time.
_PROCESSED_ID_KINDS: tuple[str, ...] = ("bundle", "envelope")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "processed_ids",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("id_kind", sa.Text(), nullable=False),
        sa.Column("recipient_node_id", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("recipient_node_id", "id", name="pk_processed_ids"),
        sa.CheckConstraint(
            "id_kind IN (" + ", ".join(f"'{k}'" for k in _PROCESSED_ID_KINDS) + ")",
            name="ck_processed_ids_id_kind_vocabulary",
        ),
    )
    op.create_index("ix_processed_ids_expires_at", "processed_ids", ["expires_at"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_processed_ids_expires_at", table_name="processed_ids")
    op.drop_table("processed_ids")
