"""widen edge type vocabulary for method kernel edges

Revision ID: aa2adabee4de
Revises: b64f87a758f3
Create Date: 2026-07-21 05:34:34.356061

Hand-written, not autogenerated (same discipline as b9e7d0e3aff6, b438bc0f8c0c,
983751ff8bb6, and b64f87a758f3). This is the FIRST migration this repository
has ever needed against the ``edges.edge_type`` CHECK constraint since its own
creation in b9e7d0e3aff6 — ``mrr.domain.repositories.EDGE_VOCABULARY`` carried
the same nineteen members, unchanged, from initial schema creation until
docs/spec/08_RESEARCH_METHOD_KERNEL.md section 3 ("Edges") added exactly four
more (task-packets/K1-T02.yaml): ``operationalizes``, ``governed_by_protocol``,
``ruled_by``, ``decided_by``.

Widens ``ck_edges_edge_type_vocabulary`` (originally created in
b9e7d0e3aff6_initial_schema_objects_and_edges_tables.py) from nineteen to
twenty-three values via drop-then-recreate — PostgreSQL has no
``ALTER ... CHECK CONSTRAINT`` in place; a CHECK constraint change is always a
drop/recreate pair, never an in-place edit. Both literal lists below are
self-contained (deliberately NOT imported from
``mrr.domain.repositories.EDGE_VOCABULARY``), for the identical reason the
initial migration's own docstring already states: "migrations are
self-contained, reviewable snapshots that must not depend on application code
that could change after this migration is committed." The twenty-three-value
``upgrade()`` list is alphabetically sorted, matching
``packages/persistence/mrr/persistence/tables.py``'s own
``sorted(EDGE_VOCABULARY)`` convention; the nineteen-value ``downgrade()``
list is copied VERBATIM from b9e7d0e3aff6's own literal (itself already
alphabetically sorted), not re-derived, so ``downgrade()`` is a genuine, exact
reversal — not merely "delete the new four by name."

``packages/persistence/mrr/persistence/tables.py`` itself needs NO source
change for this migration (task-packets/K1-T02.yaml, confirmed by direct
inspection): its own ``_EDGE_TYPE_CHECK_CLAUSE`` is computed LIVE from the
imported ``EDGE_VOCABULARY`` constant, so adding the four members there alone
already updates that in-Python table definition at import time; only this
hand-written, intentionally-frozen migration snapshot needs a new file.

``downgrade()`` WILL FAIL (as PostgreSQL itself would, via a CHECK-violation
``IntegrityError`` raised by ``ALTER TABLE ... ADD CONSTRAINT``) if any live
``edges`` row already uses one of the four new types at the moment it runs —
the same honestly-disclosed risk every CHECK-constraint narrowing carries,
disclosed here rather than silently assumed away. This is exactly why
``tests/integration/persistence/test_postgres_repositories.py``'s own new
downgrade-reversibility test downgrades a freshly migrated, still-empty
schema (no row has ever used one of the four new types before downgrading is
attempted) — downgrading a schema that already carries data using the new
edge types is an operator's own informed decision to make, not a bug in this
migration.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa2adabee4de"
down_revision: str | Sequence[str] | None = "b64f87a758f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CONSTRAINT_NAME = "ck_edges_edge_type_vocabulary"

#: The full twenty-three-value vocabulary this migration widens the
#: constraint TO (task-packets/K1-T02.yaml) — the original nineteen
#: (b9e7d0e3aff6) plus the four spec-08 section 3 method-kernel edge types,
#: alphabetically sorted (matches mrr.persistence.tables's own
#: sorted(EDGE_VOCABULARY) convention).
_EDGE_VOCABULARY_V2: tuple[str, ...] = (
    "adapted_from",
    "contextualizes",
    "contradicts",
    "corrects",
    "decided_by",
    "depends_on",
    "derived_from",
    "fails_to_replicate",
    "governed_by_protocol",
    "invalidates",
    "member_of_source_family",
    "operationalizes",
    "projected_into",
    "qualifies",
    "replicates",
    "reviews",
    "ruled_by",
    "subject_to_obligation",
    "supersedes",
    "supports",
    "transferred_from",
    "uses_source",
    "verifies",
)

#: The original nineteen-value vocabulary (b9e7d0e3aff6's own literal),
#: copied verbatim — NOT re-derived — so downgrade() is an exact,
#: byte-for-byte reversal of upgrade(), not an approximation.
_EDGE_VOCABULARY_V1: tuple[str, ...] = (
    "adapted_from",
    "contextualizes",
    "contradicts",
    "corrects",
    "depends_on",
    "derived_from",
    "fails_to_replicate",
    "invalidates",
    "member_of_source_family",
    "projected_into",
    "qualifies",
    "replicates",
    "reviews",
    "subject_to_obligation",
    "supersedes",
    "supports",
    "transferred_from",
    "uses_source",
    "verifies",
)


def _check_clause(vocabulary: tuple[str, ...]) -> str:
    return "edge_type IN (" + ", ".join(f"'{t}'" for t in vocabulary) + ")"


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(_CONSTRAINT_NAME, "edges", type_="check")
    op.create_check_constraint(_CONSTRAINT_NAME, "edges", _check_clause(_EDGE_VOCABULARY_V2))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(_CONSTRAINT_NAME, "edges", type_="check")
    op.create_check_constraint(_CONSTRAINT_NAME, "edges", _check_clause(_EDGE_VOCABULARY_V1))
