"""domain events and outbox tables

Revision ID: b438bc0f8c0c
Revises: b9e7d0e3aff6
Create Date: 2026-07-18 16:40:00.000000

Hand-written, not autogenerated (same discipline as b9e7d0e3aff6). Mirrors
packages/persistence/mrr/persistence/tables.py column-for-column:

- ``domain_events``: the append-only, tamper-evident domain event log
  (task-packets/E1-T06.yaml, MRR-NFR-002). ``sequence`` is a database
  identity column (``GENERATED ALWAYS AS IDENTITY``), so append order is
  decided by the database, never by application code. ``prev_hash`` is NULL
  only for the very first physical row ever inserted; every later row's
  ``prev_hash`` is the previous row's ``content_hash``. There is no UPDATE
  or DELETE path anywhere in ``mrr.persistence.repositories.PostgresEventLog``.
- ``outbox``: the transactional outbox coupling a state change to its
  domain event (docs/spec/03_API_AND_EVENTS.md section 5.3). ``status`` is
  constrained by a CHECK against the exact two-value vocabulary, deliberately
  hard-coded as a literal list rather than imported from mrr.provenance —
  migrations are self-contained, reviewable snapshots that must not depend on
  application code that could change after this migration is committed. The
  literal list below MUST match mrr.provenance.log.OUTBOX_STATUSES as it
  stood when this migration was authored; a future vocabulary change
  requires its own migration, not an edit to this file.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b438bc0f8c0c"
down_revision: str | Sequence[str] | None = "b9e7d0e3aff6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Verbatim snapshot of mrr.provenance.log.OUTBOX_STATUSES at authoring time.
_OUTBOX_STATUSES: tuple[str, ...] = ("dispatched", "pending")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "domain_events",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("causation_id", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=False),
        sa.Column("object_revision", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("prev_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("sequence", name="pk_domain_events"),
        sa.UniqueConstraint("id", name="uq_domain_events_id"),
    )
    op.create_index("ix_domain_events_object_id", "domain_events", ["object_id"])
    op.create_index("ix_domain_events_correlation_id", "domain_events", ["correlation_id"])

    op.create_table(
        "outbox",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("event_id", name="pk_outbox"),
        sa.ForeignKeyConstraint(["event_id"], ["domain_events.id"], name="fk_outbox_event_id"),
        sa.CheckConstraint(
            "status IN (" + ", ".join(f"'{s}'" for s in _OUTBOX_STATUSES) + ")",
            name="ck_outbox_status_vocabulary",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("outbox")

    op.drop_index("ix_domain_events_correlation_id", table_name="domain_events")
    op.drop_index("ix_domain_events_object_id", table_name="domain_events")
    op.drop_table("domain_events")
