"""key_revocations table

Revision ID: b64f87a758f3
Revises: 983751ff8bb6
Create Date: 2026-07-21 02:06:33.699094

Hand-written, not autogenerated (same discipline as b9e7d0e3aff6, b438bc0f8c0c,
and 983751ff8bb6). Mirrors packages/persistence/mrr/persistence/tables.py
column-for-column:

- ``key_revocations``: the durable, append-only revocation-fact store
  (task-packets/E5-T07b.yaml) backing ``mrr.persistence.repositories.
  PostgresKeyRevocationStore`` and the pure ``mrr.domain.trust_revocation.
  trust_revoked_after_creation`` predicate. Keyed by ``kid`` ALONE, not
  ``(practice_id, kid)`` — a kid (``mrr.crypto.keys.derive_key_id``) is
  already a content-derived, globally unique fingerprint of one specific
  Ed25519 public key, so it cannot legitimately belong to two different
  practices; "is this kid revoked" therefore has exactly one true answer,
  independent of who is asking (unlike ``processed_ids``, where the SAME id
  delivered to two different recipient nodes is legitimately not a replay at
  either, hence that table's wider two-column key). The primary key is also
  this table's UNIQUE constraint and the sole idempotency anchor
  ``PostgresKeyRevocationStore.record_revocation`` targets with
  ``INSERT ... ON CONFLICT (kid) DO NOTHING``. There is no UPDATE or DELETE
  path for this table anywhere in ``PostgresKeyRevocationStore`` — no such
  method exists on that class at all — so a row, once inserted by
  ``record_revocation``, is permanent and authoritative for the lifetime of
  the row; a second, differently-parameterized call for the same ``kid`` is
  a silent no-op that leaves the original row untouched.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b64f87a758f3"
down_revision: str | Sequence[str] | None = "983751ff8bb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "key_revocations",
        sa.Column("kid", sa.Text(), nullable=False),
        sa.Column("practice_id", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("kid", name="pk_key_revocations"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("key_revocations")
