"""initial schema: objects and edges tables

Revision ID: b9e7d0e3aff6
Revises:
Create Date: 2026-07-18 15:32:51.880701

Hand-written, not autogenerated (task-packets/E1-T05.yaml: "Migration must
be reproducible and reviewed - no autogenerate leftovers"). Mirrors
packages/persistence/mrr/persistence/tables.py column-for-column:

- ``objects``: one generic, revisioned object-store table. Primary key
  ``(id, revision)`` so every revision is a new row - there is no UPDATE or
  DELETE path anywhere in the repository implementations.
- ``edges``: one generic typed-edge table for the claim/evidence graph
  (docs/spec/02_DOMAIN_MODEL.md section 3). ``edge_type`` is constrained by
  a CHECK against the exact vocabulary, deliberately hard-coded as a literal
  list rather than imported from mrr.domain - migrations are self-contained,
  reviewable snapshots that must not depend on application code that could
  change after this migration is committed. The literal list below MUST
  match mrr.domain.repositories.EDGE_VOCABULARY as it stood when this
  migration was authored; a future vocabulary change requires its own
  migration, not an edit to this file.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9e7d0e3aff6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Verbatim snapshot of mrr.domain.repositories.EDGE_VOCABULARY at authoring
#: time (docs/spec/02_DOMAIN_MODEL.md section 3) - nineteen types.
_EDGE_VOCABULARY: tuple[str, ...] = (
    "adapted_from",
    "contextualizes",
    "contradicts",
    "corrects",
    "depends_on",
    "derived_from",
    "fails_to_replicate",
    "invalidates",
    "member_of_source_family",
    "projected_into",
    "qualifies",
    "replicates",
    "reviews",
    "subject_to_obligation",
    "supersedes",
    "supports",
    "transferred_from",
    "uses_source",
    "verifies",
)


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "objects",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("api_version", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("practice_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("supersedes", sa.Text(), nullable=True),
        sa.Column("labels", postgresql.JSONB(), nullable=True),
        sa.Column("body", postgresql.JSONB(), nullable=False),
        sa.PrimaryKeyConstraint("id", "revision", name="pk_objects"),
    )
    op.create_index("ix_objects_kind", "objects", ["kind"])

    op.create_table(
        "edges",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column("edge_type", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("practice_id", sa.Text(), nullable=True),
        sa.Column("scope", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_edges"),
        sa.CheckConstraint(
            "edge_type IN (" + ", ".join(f"'{t}'" for t in _EDGE_VOCABULARY) + ")",
            name="ck_edges_edge_type_vocabulary",
        ),
    )
    op.create_index("ix_edges_source_id", "edges", ["source_id"])
    op.create_index("ix_edges_target_id", "edges", ["target_id"])
    op.create_index("ix_edges_edge_type", "edges", ["edge_type"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_edges_edge_type", table_name="edges")
    op.drop_index("ix_edges_target_id", table_name="edges")
    op.drop_index("ix_edges_source_id", table_name="edges")
    op.drop_table("edges")

    op.drop_index("ix_objects_kind", table_name="objects")
    op.drop_table("objects")
