"""pending_deliveries table

Revision ID: cbef83b8ef50
Revises: aa2adabee4de
Create Date: 2026-07-21 06:00:00.000000

Hand-written, not autogenerated (same discipline as b9e7d0e3aff6,
b438bc0f8c0c, 983751ff8bb6, b64f87a758f3, and aa2adabee4de). Mirrors
packages/persistence/mrr/persistence/tables.py column-for-column:

- ``pending_deliveries``: the durable, per-recipient offline
  delivery-tracking store (task-packets/E6-T06.yaml) — the "durable
  pending-delivery record" half of MRR-FR-094 ("Every affected practice MUST
  receive a signed notification or a durable pending-delivery record"), the
  half task-packets/E6-T03.yaml's own ``notify_affected_practices``
  explicitly deferred. Primary key ``(recipient_node_id, notification_id)``
  is also this table's UNIQUE constraint and the sole idempotency anchor
  ``mrr.persistence.repositories.PostgresDeliveryPendingStore.
  open_pending_delivery`` targets with ``INSERT ... ON CONFLICT DO NOTHING``
  — mirrors ``processed_ids``'s own ``(recipient_node_id, id)`` shape
  exactly, substituting the correction notification's own stable
  ``notification_id``. ``status`` is constrained by a CHECK against the
  exact three-value vocabulary, deliberately hard-coded as a literal list
  rather than imported from mrr.domain — migrations are self-contained,
  reviewable snapshots that must not depend on application code that could
  change after this migration is committed. The literal list below MUST
  match mrr.domain.delivery_retry.DELIVERY_RECORD_STATUSES as it stood when
  this migration was authored; a future vocabulary change requires its own
  migration, not an edit to this file. A second CHECK constraint enforces
  that an ``exhausted`` row always carries a non-null ``exhausted_reason``
  (task-packets/E6-T06.yaml invariant: "delivery exhaustion is an explicit
  recorded outcome, never a silent give-up"). ``(status, next_retry_at)`` is
  indexed to support the retry-due query's ``status = 'pending' AND
  next_retry_at <= now`` predicate.

  Unlike ``processed_ids`` (append-then-prune-only, no UPDATE path ever),
  this table DOES have an UPDATE path — ``PostgresDeliveryPendingStore.
  record_retry_attempt``/``mark_exhausted`` mutate ``status``/
  ``attempt_count``/``last_attempted_at``/``next_retry_at``/``resolved_at``/
  ``exhausted_reason`` in place on the SAME row, which is exactly why this
  is a SEPARATE table rather than piggybacked onto ``processed_ids``
  (task-packets/E6-T06.yaml forbidden_changes). There is still no DELETE
  path anywhere in ``PostgresDeliveryPendingStore`` — a resolved
  (``delivered``/``exhausted``) record is never pruned, because the record
  itself IS the durable audit fact MRR-FR-094 requires.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbef83b8ef50"
down_revision: str | Sequence[str] | None = "aa2adabee4de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Verbatim snapshot of mrr.domain.delivery_retry.DELIVERY_RECORD_STATUSES at
#: authoring time.
_DELIVERY_RECORD_STATUSES: tuple[str, ...] = ("delivered", "exhausted", "pending")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "pending_deliveries",
        sa.Column("recipient_node_id", sa.Text(), nullable=False),
        sa.Column("notification_id", sa.Text(), nullable=False),
        sa.Column("correction_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_attempted_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("next_retry_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("notification_expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("exhausted_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint(
            "recipient_node_id", "notification_id", name="pk_pending_deliveries"
        ),
        sa.CheckConstraint(
            "status IN (" + ", ".join(f"'{s}'" for s in _DELIVERY_RECORD_STATUSES) + ")",
            name="ck_pending_deliveries_status_vocabulary",
        ),
        sa.CheckConstraint(
            "status != 'exhausted' OR exhausted_reason IS NOT NULL",
            name="ck_pending_deliveries_exhausted_has_reason",
        ),
    )
    op.create_index(
        "ix_pending_deliveries_status_next_retry_at",
        "pending_deliveries",
        ["status", "next_retry_at"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_pending_deliveries_status_next_retry_at", table_name="pending_deliveries")
    op.drop_table("pending_deliveries")
